source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
project 'CP_Example'

target 'LiveDigitalSDKExample' do
	use_frameworks!
	pod 'LiveDigitalSDK',
		:git => 'https://github.com/VLprojects/livedigital-ios-sdk-binary',
		:tag => '2.12.2'
end
